services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: postgres_docker
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9229:9229  # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres_docker
      PORT: 8080